"""create_tables

Revision ID: 288f9f9cfa36
Revises: 76ba33c9f986
Create Date: 2026-03-02 14:50:59.643533

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "288f9f9cfa36"
down_revision: Union[str, None] = "76ba33c9f986"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
